DROP TABLE IF EXISTS requests, event_compilations, events, compilations, categories, users CASCADE ;

create table if not exists users (
    id bigint generated by default as identity not null constraint users_pk primary key,
    name varchar(250) not null,
    email varchar(254) unique not null
);

create table if not exists categories (
    id bigint generated by default as identity not null constraint categories_pk primary key,
    name varchar(255) unique not null
);

create table if not exists events (
    id bigint generated by default as identity not null constraint events_pk primary key,
    annotation varchar(2000) not null,
    category_id bigint constraint events_categories_id_fk references categories,
    confirmed_requests integer,
    created_on timestamp not null,
    description varchar(7000) not null,
    event_date timestamp not null,
    initiator_id bigint constraint events_users_id_fk references users,
    lat real not null,
    lon real not null,
    paid boolean not null,
    participant_limit integer,
    published_on timestamp,
    request_moderation boolean default true,
    state varchar(120),
    title varchar(120) not null,
    views integer
);

create table if not exists requests (
    id bigint generated by default as identity not null constraint requests_pk primary key,
    requester_id bigint constraint requests_users_id_fk references users,
    event_id bigint constraint requests_events_id_fk references events,
    created timestamp not null,
    status varchar(255) not null
);

create table if not exists compilations (
    id bigint generated by default as identity not null constraint compilations_pk primary key,
    title varchar(255) not null ,
    pinned boolean not null
);

create table if not exists event_compilations (
    compilation_id bigint constraint compilations_id_fk references compilations,
    event_id bigint constraint event_id_fk references events,
    primary key (compilation_id, event_id)
);

