version: '3.8'
services:
  stats-server:
    build: ./statistics-service/server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - STATS_SERVER_URL=http://server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stat
      - SPRING_DATASOURCE_USERNAME=polzovatel
      - SPRING_DATASOURCE_PASSWORD=parol

  stats-db:
    image: postgres:15.1-alpine
    container_name: stat-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=polzovatel
      - POSTGRES_PASSWORD=parol

  ewm-service:
    build: ./ewm-service
    container_name: ewm-server
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL2=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=polzovatel
      - SPRING_DATASOURCE_PASSWORD=parol

  ewm-db:
    image: postgres:15.1-alpine
    container_name: ewm-db-container
    ports:
      - "6542:5432"
    volumes:
      - /ewm-db-container
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=polzovatel
      - POSTGRES_PASSWORD=parol




